### ISSUE TITLE
Apply indentation not only for the first line

### ISSUE THREAD

**Issue by zizo007** [neurobin/mdx_include#4]
When using mdx_include with other mkdocs extensions such as admonition it is important to apply the indentation for all the lines being included.

For example:

Suppose we have an md we would like to include:

```
My included content.
Which can have multiple
lines.

And blank lines
as well.
``` 

```
!!! note "This is only a test"
    {! included_item !}
```

Currently, this results in the following:

```
!!! note "This is only a test"
    My included content.
Which can have multiple
lines.

And blank lines
as well.
```

which is not suitable for this scenario. Instead it should generate this:

```
!!! note "This is only a test"
    My included content.
    Which can have multiple
    lines.
    
    And blank lines
    as well.
```

How about a syntax enhancement for this feature?
I would gladly develop this feature.

**Comment by neurobin** [comment]
If you do, you can introduce a new configuration option, it should not be the default behavior.

**Comment by neurobin** [comment]
> How about a syntax enhancement for this feature?

Introducing a new syntax feature, well, that sounds good.

**Comment by zizo007** [comment]
How about this changeset?
Please review and address if something is missing.
